-- A step's deadline, and what happens when it passes.
--
-- `slaHours` and `onTimeout` have been in the chain editor since the day it shipped and nothing has
-- ever read them, so a step with a 24-hour SLA waited exactly as long as a step with none. The
-- `approval-timeouts` job reads them now, and it needs three things this table could not say:
--
-- * `on_timeout` and `sla_hours` on the step itself. They cannot be read back out of the snapshot in
--   `approval_requests.chain`, because a step whose approvers resolve to nobody is dropped rather
--   than stored — so `step_index` counts the steps that were written and the spec's array counts the
--   steps that were asked for, and the two stop agreeing the moment one is dropped.
-- * `timeout_handled_at` with `timeout_action`. The sweep runs hourly against a deadline that stays
--   passed, so this is the whole of what stops one step being reminded every hour for ever. The pair
--   is also readable beside `on_timeout` without a log: `on_timeout = 'escalate'` with
--   `timeout_action = 'remind'` is an escalation that had nobody above to go to.
-- * `source` on the decision. An auto-approval is a decision and is recorded as one, but it is not a
--   person's, and a row that cannot say so is one somebody eventually reads as "her manager approved
--   it". `approver_id` carries the nil UUID, which `uuidv7()` cannot produce; this column says why.
--
-- Additive and defaulted, so the image before this one reads both tables unchanged: `on_timeout`
-- defaults to the mildest of the three actions and every step raised before today therefore only
-- ever gets reminded. Generated by drizzle-kit and then given `if not exists`, because a migration
-- re-run after an edit must be a no-op — drizzle keys applied migrations by content hash, so editing
-- any file in this folder replays every file in it.
ALTER TABLE "mod_hr"."approval_decisions" ADD COLUMN IF NOT EXISTS "source" text DEFAULT 'human' NOT NULL;--> statement-breakpoint
ALTER TABLE "mod_hr"."approval_steps" ADD COLUMN IF NOT EXISTS "on_timeout" text DEFAULT 'remind' NOT NULL;--> statement-breakpoint
ALTER TABLE "mod_hr"."approval_steps" ADD COLUMN IF NOT EXISTS "sla_hours" integer;--> statement-breakpoint
ALTER TABLE "mod_hr"."approval_steps" ADD COLUMN IF NOT EXISTS "timeout_handled_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "mod_hr"."approval_steps" ADD COLUMN IF NOT EXISTS "timeout_action" text;
