-- Subject access, erasure and retention.
--
-- Three things, one migration, and all of it additive: new nullable columns and two new tables, so
-- the image before this one reads the schema unchanged and a rollback needs no dump.
--
-- * `people.erased_at` / `erased_by` / `erasure_reason` — the erasure tombstone. Deliberately not a
--   new member of `status`: that column carries the employment lifecycle, and overloading it makes
--   "was she still employed when this was approved" unanswerable, which is the question a payroll
--   audit asks. Widening `PersonStatus` would also be a *constructing* break on a shared contract —
--   every stored row keeps parsing and every site that builds one stops compiling.
-- * `people.erased_file_ids` — the file objects an erasure had to leave behind. `core.files.get` is
--   the only file procedure a module can reach, so clearing `photo_file_id` orphans the object;
--   recording the id is what keeps that finishable instead of losing it.
-- * `sensitive_access_log` — who read a national identity number, a birth date or a bank account.
--   Written in the same transaction as the read, in HR's own schema rather than only in
--   `mod_core.activity_events`, because that table is read behind `core.audit.view` and these fields
--   are not.
-- * `retention_settings` — how long this workspace keeps each class. One row per workspace, so
--   `workspace_id` is the primary key and "one row" is the database's promise rather than a
--   convention. Every horizon is null until somebody sets one.
--
-- Generated by drizzle-kit from `src/server/schema.ts` and then given `if not exists` on every
-- statement, plus the two RLS blocks drizzle cannot express. Drizzle keys applied migrations by
-- content hash, so editing any file in this folder replays every file in it: a statement here that
-- cannot run twice takes down every module in the host service at boot, not just this one.
CREATE TABLE IF NOT EXISTS "mod_hr"."retention_settings" (
	"workspace_id" uuid PRIMARY KEY NOT NULL,
	"config" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" uuid
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mod_hr"."sensitive_access_log" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"person_id" uuid NOT NULL,
	"actor_user_id" uuid NOT NULL,
	"actor_person_id" uuid,
	"fields" text[] NOT NULL,
	"purpose" text,
	"via" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "mod_hr"."people" ADD COLUMN IF NOT EXISTS "erased_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "mod_hr"."people" ADD COLUMN IF NOT EXISTS "erased_by" uuid;--> statement-breakpoint
ALTER TABLE "mod_hr"."people" ADD COLUMN IF NOT EXISTS "erasure_reason" text;--> statement-breakpoint
ALTER TABLE "mod_hr"."people" ADD COLUMN IF NOT EXISTS "erased_file_ids" uuid[];--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_sens_access_subject_idx" ON "mod_hr"."sensitive_access_log" USING btree ("workspace_id","person_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_sens_access_actor_idx" ON "mod_hr"."sensitive_access_log" USING btree ("workspace_id","actor_user_id","created_at" DESC NULLS LAST);--> statement-breakpoint

-- Row-level security for the two new tenant tables, in the same shape as 0001 and for the same
-- reason: the API checks membership and permission first, and this is what is left when a query
-- reaches the database another way. `create policy` has no `if not exists` at all, so each one is
-- preceded by a `drop policy if exists` — without that pair, replaying this file throws, and a
-- module migration that throws stops the whole host service booting rather than only this module.
--
-- One policy per table rather than a narrower set for `sensitive_access_log`, even though that table
-- is append-only. Append-only here is the application's promise, the same way it is for `punches`
-- and `person_history`; RLS answers a different question — which workspace's rows exist at all — and
-- giving one table a different shape of policy from the other thirty-two would read as a decision
-- nobody could reconstruct.
alter table "mod_hr"."sensitive_access_log" enable row level security;--> statement-breakpoint
alter table "mod_hr"."sensitive_access_log" force row level security;--> statement-breakpoint
drop policy if exists "sensitive_access_log_ws_isolation" on "mod_hr"."sensitive_access_log";
--> statement-breakpoint
create policy "sensitive_access_log_ws_isolation" on "mod_hr"."sensitive_access_log"
  using (workspace_id::text = current_setting('app.workspace_id', true))
  with check (workspace_id::text = current_setting('app.workspace_id', true));--> statement-breakpoint

alter table "mod_hr"."retention_settings" enable row level security;--> statement-breakpoint
alter table "mod_hr"."retention_settings" force row level security;--> statement-breakpoint
drop policy if exists "retention_settings_ws_isolation" on "mod_hr"."retention_settings";
--> statement-breakpoint
create policy "retention_settings_ws_isolation" on "mod_hr"."retention_settings"
  using (workspace_id::text = current_setting('app.workspace_id', true))
  with check (workspace_id::text = current_setting('app.workspace_id', true));
