-- Onboarding and offboarding checklists: the tasks a company performs around somebody joining or
-- leaving, as a list people tick.
--
-- * `checklist_templates` — a named list per kind, at most one of which is the default that starts
--   itself for a hire or a leaver. The partial unique index is what makes "at most one" true
--   whatever else reaches the table; the service clears the previous default in the same
--   transaction so the index never has to refuse.
-- * `checklist_template_items` — the tasks, with who they fall to in the abstract (the person,
--   their manager, HR's pool, or one named person) and a due offset in days from the anchor.
-- * `checklists` — one started list for one person, **copied** from the template as it stood that
--   day. Nothing renders through the template afterwards, so editing a template changes what the
--   next joiner gets and leaves every running list exactly as it was.
-- * `checklist_items` — the copied tasks, each resolved to a real assignee (or none, for HR's pool)
--   and a real date. `overdue_notified_at` is the once-per-item marker the nightly sweep leaves,
--   the same shape `module-inventory` keeps on a warranty.
--
-- Additive throughout — four new tables and no change to anything that exists — so the image before
-- this one reads the schema unchanged and a rollback needs no dump.
--
-- Generated by drizzle-kit from `src/server/schema.ts` and then given `if not exists` on every
-- statement, plus the RLS blocks drizzle cannot express. Drizzle keys applied migrations by content
-- hash, so editing any file in this folder replays every file in it — and a module migration that
-- throws takes down every module in the host service at boot, not only this one.
CREATE TABLE IF NOT EXISTS "mod_hr"."checklist_items" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"checklist_id" uuid NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"assignee_person_id" uuid,
	"due_on" date,
	"order" integer DEFAULT 0 NOT NULL,
	"done_at" timestamp with time zone,
	"done_by" uuid,
	"note" text,
	"overdue_notified_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mod_hr"."checklist_template_items" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"template_id" uuid NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"assignee" text DEFAULT 'hr' NOT NULL,
	"assignee_person_id" uuid,
	"due_offset_days" integer DEFAULT 0 NOT NULL,
	"order" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mod_hr"."checklist_templates" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"name" text NOT NULL,
	"kind" text NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"archived_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mod_hr"."checklists" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"person_id" uuid NOT NULL,
	"template_id" uuid,
	"name" text NOT NULL,
	"kind" text NOT NULL,
	"anchor_date" date NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"started_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	"cancelled_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_checklist_items_list_idx" ON "mod_hr"."checklist_items" USING btree ("workspace_id","checklist_id","order");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_checklist_items_assignee_idx" ON "mod_hr"."checklist_items" USING btree ("workspace_id","assignee_person_id","due_on") WHERE done_at is null;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_checklist_items_due_idx" ON "mod_hr"."checklist_items" USING btree ("workspace_id","due_on") WHERE done_at is null;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_checklist_template_items_idx" ON "mod_hr"."checklist_template_items" USING btree ("workspace_id","template_id","order");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_checklist_templates_ws_idx" ON "mod_hr"."checklist_templates" USING btree ("workspace_id","kind","name");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "hr_checklist_templates_default_uq" ON "mod_hr"."checklist_templates" USING btree ("workspace_id","kind") WHERE is_default and archived_at is null;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_checklists_person_idx" ON "mod_hr"."checklists" USING btree ("workspace_id","person_id","status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_checklists_status_idx" ON "mod_hr"."checklists" USING btree ("workspace_id","status","created_at");--> statement-breakpoint

-- ---------------------------------------------------------------------------------------------
-- Row-level security for the four new tenant tables, in the same shape as 0001 and for the same
-- reason: the API checks membership and permission first, and this is what is left when a query
-- reaches the database another way. `create policy` has no `if not exists` at all, so each one is
-- preceded by a `drop policy if exists` — without that pair, replaying this file throws.
alter table "mod_hr"."checklist_templates" enable row level security;--> statement-breakpoint
alter table "mod_hr"."checklist_templates" force row level security;--> statement-breakpoint
drop policy if exists "checklist_templates_ws_isolation" on "mod_hr"."checklist_templates";
--> statement-breakpoint
create policy "checklist_templates_ws_isolation" on "mod_hr"."checklist_templates"
  using (workspace_id::text = current_setting('app.workspace_id', true))
  with check (workspace_id::text = current_setting('app.workspace_id', true));--> statement-breakpoint

alter table "mod_hr"."checklist_template_items" enable row level security;--> statement-breakpoint
alter table "mod_hr"."checklist_template_items" force row level security;--> statement-breakpoint
drop policy if exists "checklist_template_items_ws_isolation" on "mod_hr"."checklist_template_items";
--> statement-breakpoint
create policy "checklist_template_items_ws_isolation" on "mod_hr"."checklist_template_items"
  using (workspace_id::text = current_setting('app.workspace_id', true))
  with check (workspace_id::text = current_setting('app.workspace_id', true));--> statement-breakpoint

alter table "mod_hr"."checklists" enable row level security;--> statement-breakpoint
alter table "mod_hr"."checklists" force row level security;--> statement-breakpoint
drop policy if exists "checklists_ws_isolation" on "mod_hr"."checklists";
--> statement-breakpoint
create policy "checklists_ws_isolation" on "mod_hr"."checklists"
  using (workspace_id::text = current_setting('app.workspace_id', true))
  with check (workspace_id::text = current_setting('app.workspace_id', true));--> statement-breakpoint

alter table "mod_hr"."checklist_items" enable row level security;--> statement-breakpoint
alter table "mod_hr"."checklist_items" force row level security;--> statement-breakpoint
drop policy if exists "checklist_items_ws_isolation" on "mod_hr"."checklist_items";
--> statement-breakpoint
create policy "checklist_items_ws_isolation" on "mod_hr"."checklist_items"
  using (workspace_id::text = current_setting('app.workspace_id', true))
  with check (workspace_id::text = current_setting('app.workspace_id', true));
