-- The retention sweep: the switch that turns it on, and the log of every run.
--
-- * `retention_settings.sweep_enabled` — whether the nightly job acts on this workspace's horizons.
--   A column rather than a key inside `config`, because `config` is parsed through `HrRetention`
--   on every read and write and a zod object strips what it does not declare; the job reads this
--   with `where sweep_enabled` and parses nothing. Defaulted to false, so every workspace that has
--   ever set a horizon stays exactly as it was: counted, never acted on, until somebody turns it on.
-- * `retention_runs` — one row per sweep, dry or real, nightly or by hand. What each class matched,
--   what was affected, what was skipped for sitting in a locked period, every person a touched row
--   belonged to, and every document file the run orphaned in core's storage. A failed run is a row
--   too, with the error and no counts, because it rolled back and touched nothing.
--
-- Additive throughout — one defaulted column and one new table — so the image before this one
-- reads the schema unchanged and a rollback needs no dump.
--
-- Generated by drizzle-kit from `src/server/schema.ts` and then given `if not exists` on every
-- statement, plus the RLS block drizzle cannot express. Drizzle keys applied migrations by content
-- hash, so editing any file in this folder replays every file in it — and a module migration that
-- throws takes down every module in the host service at boot, not only this one.
CREATE TABLE IF NOT EXISTS "mod_hr"."retention_runs" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finished_at" timestamp with time zone,
	"dry_run" boolean DEFAULT true NOT NULL,
	"started_by" uuid,
	"per_class" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"person_ids" uuid[] DEFAULT '{}'::uuid[] NOT NULL,
	"file_ids" uuid[] DEFAULT '{}'::uuid[] NOT NULL,
	"error" text
);
--> statement-breakpoint
ALTER TABLE "mod_hr"."retention_settings" ADD COLUMN IF NOT EXISTS "sweep_enabled" boolean DEFAULT false NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_retention_runs_ws_idx" ON "mod_hr"."retention_runs" USING btree ("workspace_id","started_at" DESC NULLS LAST);--> statement-breakpoint

-- Row-level security for the new tenant table, in the same shape as 0001 and for the same reason:
-- the API checks membership and permission first, and this is what is left when a query reaches
-- the database another way. `create policy` has no `if not exists` at all, so it is preceded by a
-- `drop policy if exists` — without that pair, replaying this file throws.
alter table "mod_hr"."retention_runs" enable row level security;--> statement-breakpoint
alter table "mod_hr"."retention_runs" force row level security;--> statement-breakpoint
drop policy if exists "retention_runs_ws_isolation" on "mod_hr"."retention_runs";
--> statement-breakpoint
create policy "retention_runs_ws_isolation" on "mod_hr"."retention_runs"
  using (workspace_id::text = current_setting('app.workspace_id', true))
  with check (workspace_id::text = current_setting('app.workspace_id', true));
